apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-circleci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ArinMoyal/circleci-argocd.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp-weather
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
